[lab4]
# Укажите IP вашей ВМ и имя пользователя
vm_host ansible_host=YOUR_VM_IP ansible_user=YOUR_USERNAME ansible_ssh_private_key_file=~/.ssh/your_key_name

[lab4:vars]
# Укажите путь к python3 на целевой машине, если он отличается от стандартного
ansible_python_interpreter=/usr/bin/python3

