[lab4]
# Для запуска на той же ВМ используйте localhost
localhost ansible_connection=local

# Для удаленной ВМ используйте:
# remote_host ansible_host=192.168.1.100 ansible_user=username

[lab4:vars]
ansible_python_interpreter=/usr/bin/python3

